name: Daily Database Cleanup

on:
  schedule:
    - cron: '0 14 * * *' # 23:00 JST

jobs:
  cleanup-database:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Exec migration
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}
          command: d1 execute ${{ secrets.D1_DATABASE_NAME }} --command 'DELETE FROM webauthn_credentials; DELETE FROM users;'
